services:
  - type: web
    name: arkyn-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # or leave blank, Render overrides this at runtime
      # Add other env vars here or use dashboard
    rootDir: backend  # if backend is in 'backend' folder
